### PR TITLE
Cross compile sbuild

### PR DESCRIPTION
**Pull request by JuergenKosel**
This pull request improves cross building by using the cross tool chain of Debian 9 (stretch).
Especially it uses the tool `sbuild`, which creates a chroot environment for cross compilation.

### CODE REVIEW

**Comment by JuergenKosel** [comment]
Due to the previous pull request #49, I have now an error during cross build:

```
schroot -c stretch-amd64-sbuild -- make
[  0%] Building C object bld/src/libiotsdk/CMakeFiles/libiotsdk.dir/__/__/__/deps/shared/src/x509_openssl.c.o
/home/klj/iot-gateway-proxy/deps/shared/src/x509_openssl.c: In function 'load_certificate_chain':
/home/klj/iot-gateway-proxy/deps/shared/src/x509_openssl.c:70:28: error: dereferencing pointer to incomplete type 'SSL_CTX {aka struct ssl_ctx_st}'
                 if (ssl_ctx->extra_certs != NULL)
                            ^~
/home/klj/iot-gateway-proxy/deps/shared/src/x509_openssl.c: In function 'x509_openssl_add_certificates':
/home/klj/iot-gateway-proxy/deps/shared/src/x509_openssl.c:299:38: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
             BIO_METHOD* bio_method = BIO_s_mem();
                                      ^~~~~~~~~
bld/src/libiotsdk/CMakeFiles/libiotsdk.dir/build.make:1046: recipe for target 'bld/src/libiotsdk/CMakeFiles/libiotsdk.dir/__/__/__/deps/shared/src/x509_openssl.c.o' failed
make[2]: *** [bld/src/libiotsdk/CMakeFiles/libiotsdk.dir/__/__/__/deps/shared/src/x509_openssl.c.o] Error 1
CMakeFiles/Makefile2:197: recipe for target 'bld/src/libiotsdk/CMakeFiles/libiotsdk.dir/all' failed
make[1]: *** [bld/src/libiotsdk/CMakeFiles/libiotsdk.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by marcschier** [comment]
I am discussing with the team.  What's the version of OpensSl that is pulled in?  Best workaround is to sync the dependency to before the commit.  There is nothing that depends on any specific feature afaik.

**Comment by JuergenKosel** [comment]
Hello @marcschier 

the openssl version is  1.1.0f (see https://packages.debian.org/stretch/libssl-dev ).
I have already raised an issue in the sub-module: https://github.com/Azure/azure-c-shared-utility/issues/88 .
Because the sub-module project needs to add an include directive.

**Comment by marcschier** [comment]
That is what I thought (and just found as well ;-).  The iotsdk team only tests against 1.0.2 (k) is what I learned overnight.   I am working (with them) on a fix.  In the meantime I will revert the submodule back to the previous version that seems to be working with 1.1 and 1.0.  I added a stretch docker file which repros this issue outside of cross build.

**Comment by marcschier** [comment]
Just saw you raised the issue in c-shared.  That is great.  Then we shall track it through that issue.

**Pull request merged**
